In [1]:
import pandas as pd
import numpy as np
import math
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.svm import LinearSVC
from sklearn import preprocessing

In [2]:
loan_data = pd.read_csv('train.csv', sep=',', header=0)

In [3]:
#loan_data

In [4]:
dropped_data = loan_data[loan_data.isnull().any(axis=1)]

In [5]:
filtered_data = loan_data.dropna()

In [6]:
#filtered_data

In [7]:
# Encode categoric variables using 1 hot encoding

In [8]:
ord_enc = preprocessing.OrdinalEncoder()

In [9]:
ord_enc

OrdinalEncoder(categories='auto', dtype=<class 'numpy.float64'>)

In [10]:
#filtered_data.loc[:,['Dependents']].values

In [11]:
ordinal_encoded = ord_enc.fit_transform(filtered_data.loc[:,['Dependents']].values)

In [12]:
ordinal_encoded

array([[1.],
       [0.],
       [0.],
       [0.],
       [2.],
       [0.],
       [3.],
       [2.],
       [1.],
       [2.],
       [2.],
       [0.],
       [2.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [2.],
       [0.],
       [0.],
       [1.],
       [0.],
       [3.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [2.],
       [1.],
       [2.],
       [0.],
       [0.],
       [1.],
       [2.],
       [0.],
       [3.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [3.],
       [0.],
       [0.],
       [2.],
       [0.],
       [3.],
       [0.],
       [0.],
       [1.],
       [3.],
       [0.],
       [2.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [2.],
       [2.],
       [0.],
       [0.],
       [0.],

In [13]:
# Encode categoric variables using 1 hot encoding

In [14]:
#Change credit historya in place to categoric

In [15]:
filtered_data.loc[:,('Credit_History')] = filtered_data.loc[:,('Credit_History')].astype('str').values

/usr/local/lib/python3.7/site-packages/pandas/core/indexing.py:543: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s


In [16]:
filtered_data.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History        object
Property_Area         object
Loan_Status           object
dtype: object

In [17]:
filtered_data.sample(10)

Loan_ID  Gender Married Dependents     Education Self_Employed  \
105  LP001367    Male     Yes          1      Graduate            No   
586  LP002916    Male     Yes          0      Graduate            No   
273  LP001894    Male     Yes          0      Graduate            No   
478  LP002531    Male     Yes          1      Graduate           Yes   
196  LP001666    Male      No          0      Graduate            No   
483  LP002541    Male     Yes          0      Graduate            No   
77   LP001259    Male     Yes          1      Graduate           Yes   
82   LP001267  Female     Yes          2      Graduate            No   
511  LP002640    Male     Yes          1      Graduate            No   
28   LP001086    Male      No          0  Not Graduate            No   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
105             3052             1030.0       100.0             360.0   
586             2297             1522.0       104.0             360.0   
273             2620             2223.0       150.0             360.0   
478            16667             2250.0        86.0             360.0   
196             8333             3750.0       187.0             360.0   
483            10833                0.0       234.0             360.0   
77              1000             3022.0       110.0             360.0   
82              1378             1881.0       167.0             360.0   
511             6065             2004.0       250.0             360.0   
28              1442                0.0        35.0             360.0   

    Credit_History Property_Area Loan_Status  
105            1.0         Urban           Y  
586            1.0         Urban           Y  
273            1.0     Semiurban           Y  
478            1.0     Semiurban           Y  
196            1.0         Rural           Y  
483            1.0     Semiurban           Y  
77             1.0         Urban           N  
82             1.0         Urban           N  
511            1.0     Semiurban           Y  
28             1.0         Urban           N

In [18]:
genders = ['Male', 'Female']
married = ['Yes','No']
education = ['Not Graduate', 'Graduate']
self_employed = ['Yes','No']
credit_history = ['1.0', '0.0']
property_area = ['Rural','Semiurban', 'Urban']

In [19]:
enc = preprocessing.OneHotEncoder(categories=[genders, married, education,
                                              self_employed, credit_history, property_area], sparse=False)

In [20]:
enc

OneHotEncoder(categorical_features=None,
              categories=[['Male', 'Female'], ['Yes', 'No'],
                          ['Not Graduate', 'Graduate'], ['Yes', 'No'],
                          ['1.0', '0.0'], ['Rural', 'Semiurban', 'Urban']],
              drop=None, dtype=<class 'numpy.float64'>, handle_unknown='error',
              n_values=None, sparse=False)

In [21]:
one_hot_encoded = enc.fit_transform(filtered_data.loc[:,['Gender','Married','Education', 'Self_Employed', 
                                       'Credit_History', 'Property_Area']].values)

In [22]:
one_hot_encoded

array([[1., 0., 1., ..., 1., 0., 0.],
       [1., 0., 1., ..., 0., 0., 1.],
       [1., 0., 1., ..., 0., 0., 1.],
       ...,
       [1., 0., 1., ..., 0., 0., 1.],
       [1., 0., 1., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 1., 0.]])

In [23]:
one_hot_encoded[0]

array([1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0.])

In [24]:
one_hot_headers = ['Male', 'Female', 'Married', 'Unmarried', 
                   'Not_Graduate', 'Graduate', 'Self_Employed', 'Not_Self_Employed', 
                   'Has_Credit_History', 'No_Credit_History', 
                   'Rural', 'Semiurban', 'Urban']

In [25]:
print("Data len: %s \n Headers len: %s" %(len(one_hot_encoded[0]), len(one_hot_headers)))

Data len: 13 
 Headers len: 13


In [26]:
len(one_hot_encoded)

480

In [33]:
filtered_data.loc[:,('ApplicantIncome','ApplicantIncome', 'LoanAmount', 'Loan_Amount_Term')].values

array([[4583., 4583.,  128.,  360.],
       [3000., 3000.,   66.,  360.],
       [2583., 2583.,  120.,  360.],
       ...,
       [8072., 8072.,  253.,  360.],
       [7583., 7583.,  187.,  360.],
       [4583., 4583.,  133.,  360.]])

In [34]:
num_filtered_data = filtered_data.loc[:,('ApplicantIncome','ApplicantIncome', 
                                         'LoanAmount', 'Loan_Amount_Term')].values

In [35]:
len(num_filtered_data)

480

In [51]:
a = pd.DataFrame(num_filtered_data, columns=['ApplicantIncome','ApplicantIncome', 'LoanAmount', 'Loan_Amount_Term'])

In [52]:
b = pd.DataFrame(ordinal_encoded, columns=['Dependents'])

In [53]:
c = pd.DataFrame(one_hot_encoded, columns=one_hot_headers)

In [54]:
pd.concat([a, b, c], axis=1)

ApplicantIncome  ApplicantIncome  LoanAmount  Loan_Amount_Term  \
0             4583.0           4583.0       128.0             360.0   
1             3000.0           3000.0        66.0             360.0   
2             2583.0           2583.0       120.0             360.0   
3             6000.0           6000.0       141.0             360.0   
4             5417.0           5417.0       267.0             360.0   
5             2333.0           2333.0        95.0             360.0   
6             3036.0           3036.0       158.0             360.0   
7             4006.0           4006.0       168.0             360.0   
8            12841.0          12841.0       349.0             360.0   
9             3200.0           3200.0        70.0             360.0   
10            3073.0           3073.0       200.0             360.0   
11            1853.0           1853.0       114.0             360.0   
12            1299.0           1299.0        17.0             120.0   
13            4950.0           4950.0       125.0             360.0   
14            3510.0           3510.0        76.0             360.0   
15            4887.0           4887.0       133.0             360.0   
16            7660.0           7660.0       104.0             360.0   
17            5955.0           5955.0       315.0             360.0   
18            2600.0           2600.0       116.0             360.0   
19            9560.0           9560.0       191.0             360.0   
20            2799.0           2799.0       122.0             360.0   
21            4226.0           4226.0       110.0             360.0   
22            1442.0           1442.0        35.0             360.0   
23            3167.0           3167.0        74.0             360.0   
24            4692.0           4692.0       106.0             360.0   
25            3500.0           3500.0       114.0             360.0   
26           12500.0          12500.0       320.0             360.0   
27            3667.0           3667.0       144.0             360.0   
28            4166.0           4166.0       184.0             360.0   
29            3748.0           3748.0       110.0             360.0   
..               ...              ...         ...               ...   
450           3159.0           3159.0       108.0              84.0   
451           3229.0           3229.0       110.0             360.0   
452           1782.0           1782.0       107.0             360.0   
453           6540.0           6540.0       205.0             360.0   
454           1836.0           1836.0        90.0             360.0   
455           3166.0           3166.0        36.0             360.0   
456           2787.0           2787.0       146.0             360.0   
457           4283.0           4283.0       172.0              84.0   
458           2297.0           2297.0       104.0             360.0   
459           2165.0           2165.0        70.0             360.0   
460           2726.0           2726.0       106.0             360.0   
461           3000.0           3000.0        56.0             180.0   
462           6000.0           6000.0       205.0             240.0   
463           3859.0           3859.0       142.0             180.0   
464          16120.0          16120.0       260.0             360.0   
465           3833.0           3833.0       110.0             360.0   
466           6383.0           6383.0       187.0             360.0   
467           9963.0           9963.0       180.0             360.0   
468           5780.0           5780.0       192.0             360.0   
469           5703.0           5703.0       128.0             360.0   
470           3676.0           3676.0       172.0             360.0   
471          12000.0          12000.0       496.0             360.0   
472           3400.0           3400.0       173.0             360.0   
473           3987.0           3987.0       157.0             360.0   
474           3232.0         

In [55]:
num_cat_data = pd.concat([a, b, c], axis=1)

In [56]:
# Data Variations to run:
# 1 - No standardisation
# 2 - Normalise numeric fields (income data, term, dependents)
# 3 - Normalise all fields using MaxAbsScaler
# 4 - Only use MaxAbsScaler on encoded data

In [57]:
num_cat_data.values

array([[4.583e+03, 4.583e+03, 1.280e+02, ..., 1.000e+00, 0.000e+00,
        0.000e+00],
       [3.000e+03, 3.000e+03, 6.600e+01, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       [2.583e+03, 2.583e+03, 1.200e+02, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       ...,
       [8.072e+03, 8.072e+03, 2.530e+02, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       [7.583e+03, 7.583e+03, 1.870e+02, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       [4.583e+03, 4.583e+03, 1.330e+02, ..., 0.000e+00, 1.000e+00,
        0.000e+00]])

In [58]:
X = num_cat_data.values

In [60]:
filtered_data.loc[:,('Loan_Status')].values

array(['N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'N', 'Y',
       'Y', 'N', 'N', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'Y',
       'N', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y',
       'N', 'N', 'N', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N',
       'N', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'Y',
       'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'N', 'Y',
       'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N',
       'N', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y',
       'N', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'N', 'Y',
       'N', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'N', 'Y', 'N', 'N', 'Y', 'N',
       'Y', 'Y', 'N', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'N', 'Y', 'N', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'Y', 'Y', 'Y',
       'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y

In [61]:
y = filtered_data.loc[:,('Loan_Status')].values

In [64]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [65]:
# Train model on:
# 1 - All features
# 2 - No new features

In [66]:
# Models to test
# A - Support Vector Classifier

In [67]:
# Linear SVC

In [81]:
svc_clf = LinearSVC(tol=1e-5,max_iter=20000)

In [82]:
scores = cross_val_score(svc_clf, X_train, y_train, cv=10)

/usr/local/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/usr/local/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/usr/local/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/usr/local/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/usr/local/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [83]:
scores

array([0.33333333, 0.33333333, 0.6875    , 0.6875    , 0.3125    ,
       0.6875    , 0.6875    , 0.3125    , 0.6875    , 0.5483871 ])

In [84]:
scores.mean()

0.527755376344086

In [85]:
# 2 - Normalise numeric fields (income data, term, dependents)

In [87]:
from sklearn import preprocessing

In [88]:
num_filtered_data.mean(axis=0)

array([5364.23125   , 5364.23125   ,  144.73541667,  342.05      ])

In [89]:
num_filtered_data.std(axis=0)

array([5662.34374386, 5662.34374386,   80.42425782,   65.14443568])

In [90]:
num_filtered_data_scaled = preprocessing.scale(num_filtered_data)

In [91]:
num_filtered_data_scaled

array([[-0.13796959, -0.13796959, -0.20808917,  0.27554157],
       [-0.4175358 , -0.4175358 , -0.97900085,  0.27554157],
       [-0.49118022, -0.49118022, -0.30756164,  0.27554157],
       ...,
       [ 0.47820635,  0.47820635,  1.34616826,  0.27554157],
       [ 0.39184635,  0.39184635,  0.52552034,  0.27554157],
       [-0.13796959, -0.13796959, -0.14591887,  0.27554157]])

In [94]:
print("Mean: %s Standard Deviation: %s" % (num_filtered_data_scaled.mean(axis=0),
                                           num_filtered_data_scaled.std(axis=0)))

Mean: [ 2.59052039e-17  2.59052039e-17 -1.55431223e-16 -2.14643118e-16] Standard Deviation: [1. 1. 1. 1.]


In [95]:
a = pd.DataFrame(num_filtered_data_scaled, columns=['ApplicantIncome','ApplicantIncome', 'LoanAmount', 'Loan_Amount_Term'])
b = pd.DataFrame(ordinal_encoded, columns=['Dependents'])
c = pd.DataFrame(one_hot_encoded, columns=one_hot_headers)

In [96]:
num_cat_data = pd.concat([a, b, c], axis=1)

In [97]:
X = num_cat_data.values

In [98]:
y = filtered_data.loc[:,('Loan_Status')].values

In [99]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [108]:
svc_clf = LinearSVC(tol=1e-5,max_iter=5000)

In [109]:
scores = cross_val_score(svc_clf, X_train, y_train, cv=10)

In [110]:
scores

array([0.87878788, 0.81818182, 0.78787879, 0.6969697 , 0.84375   ,
       0.90625   , 0.75      , 0.83870968, 0.74193548, 0.80645161])

In [111]:
scores.mean()

0.806891495601173

In [112]:
svc_clf.fit(X_train, y_train)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=5000,
          multi_class='ovr', penalty='l2', random_state=None, tol=1e-05,
          verbose=0)

In [116]:
svc_clf.score(X_test,y_test)

0.8050314465408805